# Generated by Django 5.1.4 on 2025-01-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.IntegerField(max_length=100),
        ),
    ]
    
