# Generated by Django 5.1.4 on 2025-02-04 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 11, 56, 56, 410494, tzinfo=datetime.timezone.utc)),
        ),
    ]
