# Generated by Django 5.1.5 on 2025-02-06 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
